name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose --all-features
    - name: Build
      run: cargo build --verbose --all-features
    - name: Test
      run: cargo test --verbose --all-features -- --test-threads 1
    - name: Fmt
      run: cargo fmt --check
